### PR TITLE
Upgrading to python 3.12 after dependency cleanup

### PR DESCRIPTION
**Pull request by bcdurak**
## Pre-requisites

Please ensure you have done the following:

- [X] I have read the **CONTRIBUTING.md** document.
- [X] If my change requires a change to docs, I have updated the documentation
      accordingly.
- [ ] I have added tests to cover my changes.
- [X] I have based my new branch on `develop` and the open PR is targeting
      `develop`. If your branch wasn't based on develop read
      [Contribution guide on rebasing branch to develop](https://github.com/zenml-io/mlstacks/blob/main/CONTRIBUTING.md#-pull-requests-rebase-your-branch-on-develop).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      change)
- [ ] Other (add details above)

### CODE REVIEW

**Review by strickvl — APPROVED** [review]
LGTM

**Comment by strickvl** [comment]
@bcdurak you have one failing test, though, here.

**Comment by bcdurak** [comment]
@strickvl I guess it is due to an expired key:

```
│ Error: Failed to install provider
│ 
│ Error while installing gavinbunney/kubectl v1.14.0: error checking
│ signature: openpgp: key expired
```
Do you have any idea where I can start digging?

**Comment by strickvl** [comment]
@bcdurak https://github.com/gavinbunney/terraform-provider-kubectl/issues/297

**Comment by bcdurak** [comment]
@strickvl I applied the recommended approach but I ended up changing 45 more files. Would be great if you could take a second look :D

**Pull request merged**
